# This is a basic workflow to help you get started with Actions

name: do-stuff

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job01:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - uses: mscoutermarsh/ascii-art-action@master
      with:
        text: 'NUS ACE BATCH 15'

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        date
        ls -la
        uname -a
        df -h
        which wget
        which curl
        curl -X POST 'https://zdtdtxajzydjqzuktnqx.functions.supabase.co/telegram-bot?secret=${{ secrets.FUNCTION_SECRET }}' -H "Content-Type: application/json" -d '{"update_id":831767500,"message":{"message_id":110,"from":{"id":1027371062,"is_bot":false,"first_name":"Thor ⚡️","last_name":"@thorwebdev","username":"thorwebdev","language_code":"en"},"chat":{"id":1027371062,"first_name":"Thor ⚡️","last_name":"@thorwebdev","username":"thorwebdev","type":"private"},"date":1653355484,"text":"/ping","entities":[{"offset":0,"length":6,"type":"bot_command"}]}}'
